POST http://localhost:3000/auth/register/
Content-Type: application/json

{
  "email": "lionelmessi@gmail.com",
  "password": "holyinfant",
}

POST http://localhost:3000/auth/login/
Content-Type: application/json

{
    "email": "lionelmessi@gmail.com",
    "password": "holyinfant"
}